"""
Builds a beautiful HTML email from recommendations and sends it via Gmail SMTP.
"""

import os
import smtplib
from datetime import date
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


# ── Colour palette per category ───────────────────────────────────────────────

CATEGORY_CONFIG = {
    "movies_not_seen": {
        "label":   "Movies You Haven't Seen",
        "icon":    "🎬",
        "accent":  "#E8B923",  # IMDb gold
        "bg":      "#1a1a2e",
        "badge_bg": "#E8B923",
        "badge_fg": "#000000",
    },
    "tv_not_seen": {
        "label":   "TV Series You Haven't Seen",
        "icon":    "📺",
        "accent":  "#16213E",
        "bg":      "#16213E",
        "badge_bg": "#4A90D9",
        "badge_fg": "#ffffff",
    },
    "hidden_gems": {
        "label":   "Hidden Gems & Underrated Picks",
        "icon":    "💎",
        "accent":  "#0F3460",
        "bg":      "#0F3460",
        "badge_bg": "#2ECC71",
        "badge_fg": "#ffffff",
    },
    "recent_releases": {
        "label":   "Recent Releases (2024–2025)",
        "icon":    "🆕",
        "accent":  "#533483",
        "bg":      "#533483",
        "badge_bg": "#E74C3C",
        "badge_fg": "#ffffff",
    },
    "french_titles": {
        "label":   "French Films & Series",
        "icon":    "🇫🇷",
        "accent":  "#2C3E50",
        "bg":      "#2C3E50",
        "badge_bg": "#3498DB",
        "badge_fg": "#ffffff",
    },
}

# Order in which categories appear
CATEGORY_ORDER = [
    "movies_not_seen",
    "tv_not_seen",
    "hidden_gems",
    "recent_releases",
    "french_titles",
]


# ── HTML Building Blocks ──────────────────────────────────────────────────────

HTML_HEAD = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Your Monthly IMDb Recommendations</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         background: #0d0d0d; color: #e0e0e0; }
  .wrapper { max-width: 680px; margin: 0 auto; padding: 16px; }

  /* Header */
  .header { background: linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%);
             border-radius: 16px; padding: 40px 32px; text-align: center;
             border: 1px solid #333; margin-bottom: 24px; }
  .header-logo { font-size: 48px; margin-bottom: 12px; }
  .header h1 { font-size: 28px; font-weight: 800; color: #E8B923;
               letter-spacing: -0.5px; margin-bottom: 8px; }
  .header p { font-size: 15px; color: #999; }
  .header .date-badge { display: inline-block; background: #E8B923; color: #000;
                         font-weight: 700; font-size: 13px; padding: 4px 14px;
                         border-radius: 20px; margin-top: 12px; }

  /* Section header */
  .section { margin-bottom: 32px; }
  .section-header { border-radius: 12px 12px 0 0; padding: 20px 24px;
                    display: flex; align-items: center; gap: 12px; }
  .section-icon { font-size: 28px; }
  .section-title { font-size: 20px; font-weight: 700; color: #fff; }

  /* Card */
  .card { background: #1e1e1e; border: 1px solid #2a2a2a; padding: 20px 22px;
          border-left: 4px solid transparent; transition: all 0.2s; }
  .card:last-child { border-radius: 0 0 12px 12px; }
  .card-top { display: flex; justify-content: space-between;
               align-items: flex-start; gap: 12px; margin-bottom: 10px; }
  .card-title { font-size: 17px; font-weight: 700; color: #f0f0f0; }
  .card-year { font-size: 14px; color: #888; font-weight: 400; margin-left: 6px; }
  .rating-badge { display: inline-block; font-size: 13px; font-weight: 800;
                  padding: 4px 10px; border-radius: 6px; white-space: nowrap;
                  flex-shrink: 0; }
  .card-reason { font-size: 14px; color: #bbb; line-height: 1.65;
                 margin-bottom: 14px; }
  .imdb-btn { display: inline-block; text-decoration: none; font-size: 13px;
              font-weight: 700; padding: 7px 16px; border-radius: 6px;
              background: #E8B923; color: #000; }

  /* Footer */
  .footer { text-align: center; padding: 32px 16px; color: #555; font-size: 13px; }
  .footer a { color: #E8B923; text-decoration: none; }

  /* Mobile */
  @media (max-width: 480px) {
    .wrapper { padding: 8px; }
    .header { padding: 28px 20px; }
    .header h1 { font-size: 22px; }
    .card { padding: 16px; }
    .card-top { flex-direction: column; gap: 8px; }
  }
</style>
</head>
<body>
<div class="wrapper">
"""

HTML_FOOT = """
  <div class="footer">
    <p>Generated by Claude AI · <a href="https://www.imdb.com/user/ur4016761/ratings/">Your IMDb Ratings</a></p>
    <p style="margin-top:6px;">Sent monthly — unsubscribe by disabling the GitHub Actions workflow.</p>
  </div>
</div>
</body>
</html>"""


def render_card(rec: dict, accent: str, badge_bg: str, badge_fg: str) -> str:
    title = rec.get("title", "Unknown")
    year = rec.get("year", "")
    rating = rec.get("imdb_rating", "N/A")
    url = rec.get("imdb_url", "#")
    reason = rec.get("reason", "")

    return f"""
    <div class="card" style="border-left-color: {accent};">
      <div class="card-top">
        <div>
          <span class="card-title">{title}</span>
          <span class="card-year">({year})</span>
        </div>
        <span class="rating-badge" style="background:{badge_bg}; color:{badge_fg};">
          ★ {rating}
        </span>
      </div>
      <p class="card-reason">{reason}</p>
      <a href="{url}" class="imdb-btn" target="_blank">View on IMDb →</a>
    </div>"""


def render_section(category: str, recommendations: list) -> str:
    cfg = CATEGORY_CONFIG.get(category, CATEGORY_CONFIG["movies_not_seen"])
    cards_html = "".join(
        render_card(rec, cfg["accent"], cfg["badge_bg"], cfg["badge_fg"])
        for rec in recommendations
    )
    return f"""
  <div class="section">
    <div class="section-header" style="background: {cfg['bg']};">
      <span class="section-icon">{cfg['icon']}</span>
      <span class="section-title">{cfg['label']}</span>
    </div>
    {cards_html}
  </div>"""


def build_html(recommendations: dict, report_date: str) -> str:
    header = f"""
  <div class="header">
    <div class="header-logo">🎬</div>
    <h1>Your Monthly Movie Picks</h1>
    <p>Personalised recommendations based on your 1,031+ IMDb ratings</p>
    <span class="date-badge">{report_date}</span>
  </div>"""

    sections = ""
    for cat in CATEGORY_ORDER:
        recs = recommendations.get(cat, [])
        if recs:
            sections += render_section(cat, recs)

    return HTML_HEAD + header + sections + HTML_FOOT


# ── Send ──────────────────────────────────────────────────────────────────────

def send_email(recommendations: dict) -> None:
    gmail_address = os.environ["GMAIL_ADDRESS"]
    gmail_app_password = os.environ["GMAIL_APP_PASSWORD"]
    report_date = date.today().strftime("%B %Y")

    html_body = build_html(recommendations, report_date)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Your IMDb Picks for {report_date} 🎬"
    msg["From"] = f"IMDb Recommender <{gmail_address}>"
    msg["To"] = gmail_address

    # Plain-text fallback
    plain = f"Your personalised IMDb recommendations for {report_date}.\n\n"
    for cat in CATEGORY_ORDER:
        cfg = CATEGORY_CONFIG.get(cat, {})
        plain += f"\n{cfg.get('label', cat).upper()}\n" + "─" * 40 + "\n"
        for rec in recommendations.get(cat, []):
            plain += (
                f"  • {rec['title']} ({rec['year']}) ★ {rec['imdb_rating']}\n"
                f"    {rec['imdb_url']}\n"
                f"    {rec['reason']}\n\n"
            )

    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    print(f"Sending email to {gmail_address}…")
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(gmail_address, gmail_app_password)
        server.sendmail(gmail_address, gmail_address, msg.as_string())
    print("Email sent successfully.")


if __name__ == "__main__":
    import json, sys
    from dotenv import load_dotenv
    load_dotenv()
    recs_file = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("recommendations.json")
    from pathlib import Path
    with open(recs_file) as f:
        recs = json.load(f)
    send_email(recs)
